### PR TITLE
more additions

### PR DESCRIPTION
**Pull request by tpunt**
I've done a bit more on the BC breaks section (and will continue to work on it in the coming days).

I'm not sure how thorough I should be though. Should I mention **everything** that has the potential to break 5.x code, or just the more likely ones? I'm mentioning everything at the moment, but I've noticed that this includes all of the newly introduced classes/functions/constants (which is unlikely to break existing code, especially constants in particular though). Plus none of the other migration guides have bothered to mention these unlikely breaks. Thoughts?

### CODE REVIEW

**Comment by Sobak** [comment]
Hi.

I would rather avoid this duplication, for the fact of consistency. Maybe I'm too optimistic, but people should understand that new functions/constants are now reserved. Optionally, we could add notes like _"the following functions are added to PHP and thus are now reserved names"_ or just leave sections for the forbidden names, like you did it, but place a link there, instead of duplicating a list.

Just my two cents.

**Comment by tpunt** [comment]
Good point. I've removed those sections now.

**Comment by tpunt** [comment]
I think this can be merged now - further changes can be done when the migration guide has been put up on php.net.

EDIT: I'll add in the "Removed Extensions and SAPIs" section first
EDIT2: Done

**Comment by tpunt** [comment]
@Sobak ready for merge now

**Comment by Sobak** [comment]
Merged and will be put on php.net in a couple of minutes. Thank you!

**Pull request merged**
